### PR TITLE
Use default fallbacks when `DB_CONNECTION` or `DB_DATABASE` are missing

### LINKED ISSUE #163: Recommended update script doesn't work without DB_CONNECTION
### Current Behavior

The script stops when it didn't find the DB_CONNECTION env variable when using SQLite

Terminal Image

### Expected Behavior

Update works fine without DB_CONNECTION, since SQLite is supported

### Steps to Reproduce

- Run `sudo bash -c "$(curl -fsSL https://pelican.dev/updatePanel.sh)"` on a Pelican SQLite instance without DB_CONNECTION defined in /var/www/pelican/.env

### Panel Version

1.0.0-beta24

### Wings Version

v1.0.0-beta16

### Games and/or Eggs Affected

none

### Docker Image

none

### Error Logs

```bash

```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

### PR DESCRIPTION
**Pull request by rmartinoscar**
Closes #163 

## Summary by CodeRabbit

* **Bug Fixes**
  * Update no longer aborts when DB settings are missing; it defaults to SQLite and continues using a database.sqlite path.
  * Backup, download, and restore flows now proceed in misconfigured environments instead of exiting early.
  * Restores and asset backups (avatars/fonts) are only attempted when backups exist, with clear success/failure messages.
  * Logging improved: default values are announced, explicit settings are logged only when provided.

### CODE REVIEW

File: static/updatePanel.sh [hunk 1]
```diff
@@ -46,8 +46,8 @@ echo "Panel is now in maintenance mode."
 db_connection=$(grep "^DB_CONNECTION=" "$env_file" | cut -d '=' -f 2)
 
 if [ -z "$db_connection" ]; then
-  echo "DB_CONNECTION not found in $env_file."
-  exitInstall 0
+  db_connection='sqlite'
+  echo "DB_CONNECTION not found in $env_file using $db_connection as default."
 fi
 
 echo "DB_CONNECTION is set to: $db_connection"
```
Comment (Boy132) [inline static/updatePanel.sh:53]: Just a small nitpick, but can you put the other echo inside an `else`? Otherwise it prints twice.

**Review by Boy132 — COMMENTED** [review]
Another small nitpick :x
Otherwise looks good
